# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - checkout

      - run:
          name: Monitor memory usage
          command: |
            echo "Memory Usage" > /tmp/memusage
            echo "============" >> /tmp/memusage
            free -h -s 3 >> /tmp/memusage
          background: true

      - run:
          name: Fetching submodules
          command: |
            [[ -f fuzzy-sat/.git ]] || (git submodule sync && git submodule update --init --recursive)

      - run:
          name: Init cmake build
          command: |
            mkdir build_cmake || true
            cd build_cmake
            cmake .. -DCMAKE_BUILD_TYPE=Release

      - restore_cache:
          key: fuzzolic-z3-{{ checksum ".git/modules/fuzzolic-z3/refs/heads/fuzzolic" }}

      - run:
          name: Building z3
          command: |
            cd build_cmake/fuzzolic-z3
            [ ! -f z3 ] && make -j 5 || true

      - save_cache:
          paths:
            - build_cmake/fuzzolic-z3
          key: fuzzolic-z3-{{ checksum ".git/modules/fuzzolic-z3/refs/heads/fuzzolic" }}

      - run:
          name: Building fuzzy
          command: |
            cd build_cmake/lib
            make -j 5
            cd ../tools
            make -j 5

      - run:
          name: Tests
          command: |
            cd tests
            FUZZY_BIN="`pwd`/../build_cmake/tools/fuzzy-solver" python3 -m pytest run.py --junitxml=test-results/junit.xml

      - store_test_results:
           path: tests/test-results

      - store_artifacts:
          path: /tmp/memusage
          destination: memory-usage

      - run:
          name: Job memory usage
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always
